# Generated by Django 4.2 on 2025-11-02 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0002_maintenancerequest_selected_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.TextField(help_text='JSON list of request IDs')),
                ('token', models.CharField(default='ca7e13e5eaa44223902bcc054d23d894', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.FloatField(default=0)),
                ('selected', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='maintenance_app.quotationbatch')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance_app.quotationresponse')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance_app.maintenancerequest')),
            ],
        ),
    ]
